CHANGELOG.md, README.md, client.go, client_test.go
Add capability to customize client.
#2 from @keitwb asked about configuring the HTTP client. Such customizations are common and I've used [this pattern](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) in the past to make friendly configuration with good defaults.
This PR adds configuration of the base API URL and the HTTP client, per @keitwb's request.
=> Add options to configure client

integration.go, integration_test.go, testdata/fixtures/integration/get_success.json
Adds `GetIntegration` and `DeleteIntegration`. These are needed for the Terraform provider's testing.
We need to verify that Integrations are created correctly. The content can be all over the map, so we'll defer that for now.
=> Add integration in a partial way

dashboard/model_charts_single_filter.go, dashboard/model_event_overlay_filter.go, dashboard/string_or_slice.go, testdata/fixtures/dashboard/search_success.json
Implements a custom JSON unmarshaller for `source.value`.
In #21 I "fixed" the problem in #18. Turns out it can be either a string or an array of strings. The API documentation doesn't state this, but after doing some digging I found it in the API source.
I left in a string *and* an array of strings version to qualify that this does the job.
=> Adjust type of source's value, can be string or slice

dashboard_group/model_dashboard_config.go, dashboard_group/model_dashboard_group.go, testdata/fixtures/dashboardgroup/create_success.json, testdata/fixtures/dashboardgroup/get_success.json, testdata/fixtures/dashboardgroup/update_success.json
Adds `dashboardConfigs` to DashboardGroup.
Needed for setting up mirrored dashboards.
=> Add dashboardConfigs support to dashboard groups

CHANGELOG.md, team/model_opsgenie_notification.go, testdata/fixtures/team/create_success.json, testdata/fixtures/team/get_success.json, testdata/fixtures/team/search_success.json, testdata/fixtures/team/update_success.json
Removes `credentialName` from OpsGenie
Not a real field!
=> Remove credentialName

CHANGELOG.md, signalflow/client.go, signalflow/messages/types.go
Also fix handling of stringification of unknown messages so they don't panic
=> signalflow client: Ignore keep alive events

signalflow/computation.go, signalflow/computation_test.go, signalflow/example/main.go, signalflow/fake_backend.go
This is exposed via the Computation.Expirations method as a channel.
Also allow fake backend to delete tsid data.
=> signalflow: Add TSID expiry notifications

CHANGELOG.md, orgtoken.go, orgtoken_test.go
URL encode token names in operations.
Stop having 404s all over the place. This is causing the Terraform provider to re-create existing org tokens.
=> URL encode token names

CHANGELOG.md, alertmuting_test.go, aws_cloudwatch_integration_test.go, azure_integration_test.go, chart_test.go, client.go, client_test.go, dashboard_test.go, dashboardgroup_test.go, detector_test.go, gcp_integration_test.go, integration_test.go, jira_integration_test.go, metrics_metadata_test.go, opsgenie_integration_test.go, organization_test.go, orgtoken_test.go, pagerduty_integration_test.go, sessiontoken.go, sessiontoken/model_create_token_request.go, sessiontoken/model_token.go, sessiontoken_test.go, slack_integration_test.go, team_test.go, testdata/fixtures/sessiontoken/create_success.json, victor_ops_integration_test.go
Allows users of the library to create / delete session tokens, as per https://developers.signalfx.com/sessiontokens_reference.html
=> Added support for the Session Token API

CHANGELOG.md, integration/model_aws_cloud_watch_integration.go, testdata/fixtures/integration/create_aws_success.json
Add `sfxAwsAccountArn` field.
This field was added to improve Terraform's use of the the AWS/integration API.
=> Add sfxAwsAccountArn field

writer/datapoint_writer.gen.go, writer/span_writer.gen.go, writer/template/writer.go
This manual alignment is required by the atomic package for methods like
atomic.AddInt64 to work properly on 32-bit systems.
=> Align int64 counters in writer to 64-bit boundaries

signalflow/client.go
When reusing a `Client` instance over the course of multiple `(c *Client) Execute` calls, the lack of a mutex in `client.go` causes a data race.
I wrote an example program at: https://gist.github.com/rma-stripe/efe7d7b650baae4c3a1a7a71f6eb1462
To run:
```
> SFX_AUTH_TOKEN=... go run -race reproduce_race.go
2020/03/11 11:39:18 data('system.uptime', filter=partition_filter(1, 50) and filter('host_type', 'omg')).count().publish()
2020/03/11 11:39:18 data('system.uptime', filter=partition_filter(1, 50) and filter('host_type', 'omg')).count().publish()
2020/03/11 11:39:18 data('system.uptime', filter=partition_filter(1, 50) and filter('host_type', 'omg')).count().publish()
2020/03/11 11:39:18 data('system.uptime', filter=partition_filter(1, 50) and filter('host_type', 'omg')).count().publish() …
```
=> wrap Client.channelsByName in mutex

signalflow/computation.go, signalflow/computation_test.go
Based on the signalfx-python implementation[0][1], which always exposes a code and sometimes exposes a message/error type (if they are available).
[0] https://github.com/signalfx/signalfx-python/blob/cfbda55989bc0e7ff48be82f2510f378d97d30c6/signalfx/signalflow/ws.py#L311-L314
[1] https://github.com/signalfx/signalfx-python/blob/cfbda55989bc0e7ff48be82f2510f378d97d30c6/signalfx/signalflow/errors.py#L28-L35
=> implement ComputationError struct, so applications can index into error metadata

chart/model_axes.go, chart/model_color_scale.go, chart/model_secondary_visualization.go
Change precision
The original OpenAPI spec that generated these was marked `float32` which is inaccurate as the underlying Java data types are `Double`.
=> Fix precision of various fields

datalink/model_target.go
Fixes bug in setting data link's `isDefault`.
=> Adjust omission of isDefault for data link targets

detector.go
For endpoint `/v2/detector`, `name` is ignored if it is blank:
> If the string is empty, it's ignored and the API uses the other criteria in the query.
But the same is not true for `tags`, which will return an empty list. To work around this, we ignore the value of `tags` if it is empty.
=> make SearchDetectors "tags" optional

chart.go
Like https://github.com/signalfx/signalfx-go/pull/77, but for the `/chart` endpoint. 
`name` and `tags` are both optional values that are ignored if empty. This pull request updates `SearchCharts` to drop both parameters if empty, to return the documented results instead of an empty list.
=> Make "tags" and "name" optional for SearchCharts

.circleci/config.yml, CHANGELOG.md, alertmuting.go, aws_cloudwatch_integration.go, azure_integration.go, chart.go, dashboard.go, dashboardgroup.go, datalink.go, detector.go, gcp_integration.go, integration.go, jira_integration.go, metrics_metadata.go, opsgenie_integration.go, organization.go, orgtoken.go, pagerduty_integration.go, sessiontoken.go, slack_integration.go, team.go, victor_ops_integration.go, webhook_integration.go
Makes the following changes
* More thoroughly ensures the body of a response is closed
* Does a final read of the body to empty it out, just in case (this wasn't being done for some bodies with no expected content)
There have been some reports of hanging in the Terraform provider and I decided to go over our HTTP client use with a fine-tooth comb. Turns out there are definitely some places where this could happen.
=> Adjust close to check for non-nil and be before returns on errors

CHANGELOG.md, writer/internal.go, writer/template/gen.sh, writer/template/writer.go
This will make it easier to use in external repos
=> Move go:generate comment out of writer template

signalflow/computation.go, signalflow/messages/info.go
Added two more [info messages](https://developers.signalfx.com/signalflow_analytics/rest_api_messages/information_messages_specification.html).
These don't have `int` content, so I made them `bool`s like how it's done in [signalfx-python](https://github.com/signalfx/signalfx-python/blob/f37ec439fd80c744e0e51dfcc1fb2426dadb6d3a/signalfx/signalflow/computation.py#L206)
=> Added MatchedNoTimeseries & GroupByMissingProperty

signalflow/messages/info.go
Fixes busted test
Missed this test being broken. Can't cast a `[]interface{}` directly without casting each item.
cc @shrivu-stripe
=> Fix property name test

signalflow/computation.go
- Wrap computation reads and writes in updateSignal lock
- Fix panic when reading metadata while processData is writing
Resolves #96 
Before:
`~/signalfx-go/signalflow$ go test -race ./...`
<details>
<summary>Click to expand test output</summary>
```
2020/06/19 13:03:41 Executing SignalFlow program data('cpu.utilization').publish() with tsids [] and handle handle-0
==================
WARNING: DATA RACE
Write at 0x00c000170548 by goroutine 22:
github.com/signalfx/signalfx-go/signalflow.(*Computation).processMessage()
/Users/kerby.hughes/signalfx-go/signalflow/computation.go:243 +0x2d8
github.com/signalfx/signalfx-go/signalflow.(*Computation).watchMessages()
/Users/kerby.hughes/signalfx-go/signalflow/computation.go:219 +0x1a1
Previous read at 0x00c000170548 by goroutine 8: …
```
=> Fix data races on shared Computation properties

CHANGELOG.md, signalflow/channel.go, signalflow/client.go
Messages that came in after the channel closed were casuing a panic
by sending to a closed channel.  This will ensure no messages are
sent to a channel after it is closed on client shutdown.
Fixes #98.
=> signalflow: Handle race on client close

signalflow/computation.go
This helps prevent panics when shutting down a computation.
Fixes #98.
=> signalflow: close computation data channel in writer goroutine

detector/model_incident.go
What it says on the tin.
This option actually isn't documented in the API, can it be? Looks like it is in fact there!
https://developers.signalfx.com/detectors_reference.html#operation/Retrieve%20Incidents%20Single%20Detector
=> Add detector name to incident model

signalflow/computation.go, signalflow/conn.go
Changes:
- `bufferDataMessage`: Function now returns if context is cancelled while waiting for receive on `c.dataChBuffer`
- `bufferExpirationMessages`: Function now returns if context is cancelled while waiting for receive on `c.expirationChBuffer`
- `readNextMessage`: Function now returns if context is cancelled while blocked trying to send error to `c.readErrCh`, which may no longer have a receiver after `func (c *wsConn) Run()` returns.
While using the signalflow client we noticed a resource leak in our application.
Inspection with `pprof.Lookup("goroutine")` stack traces indicated that goroutines spawned by the `Computation` and `wsConn` functions were running indefinitely even though the client context was being cancelled with `func (c *Client) Close()`. This also prevented the …
=> Close goroutines when client context is cancelled

team/model_create_update_team_request.go, team/model_team.go, testdata/fixtures/team/create_success.json, testdata/fixtures/team/get_success.json, testdata/fixtures/team/search_success.json, testdata/fixtures/team/update_success.json
Adds `detectors` and `dashboardGroups` to team
Adding new methods, as manipulating these on detectors and dashboardgroups is deprecated.
=> Add new team fields

CHANGELOG.md, chart/model_create_update_chart_request.go
What it says on the tin.
The API isn't clearing chart descriptions when this field is omitted, so send it explicitly to make sure that the lack of a description is honored.
=> Don't omit empty description for charts

signalflow/computation.go
This change fixes a switch statement in `signalflow.Computation.processMessage()` for incoming SignalFlow control messages, which should dispatch on Event (e.g  `CHANNEL_ABORT`, `END_OF_CHANNEL`), not Type, which is already determined in the outer type-switch. 
The bug meant a computation with a Stop time specified could never be understood to be completed when receiving the `END_OF_CHANNEL` or `CHANNEL_ABORT` control messages from the Signalflow API. We confirmed that a `Computation.Done()` will properly yield after receiving `END_OF_CHANNEL` with this fix.
=> Fix processing ControlMessage in signalflow.Computation

signalflow/fake_backend.go
Currently, a program error added by the client via `AddProgramError(program, errormsg)` does not come back from the fake_backend because it does not have a channel.
=> Add channel to fake_backend program error message

.circleci/config.yml, signalflow/computation.go, signalflow/computation_test.go, signalflow/messages/control.go, signalflow/messages/json.go, signalflow/messages/types_test.go
A previous fix didn't seem to be working in all cases so this should
resolve it fully.
=> signalflow: Fix channel end/abort control message handling

CHANGELOG.md, integration/model_pager_duty_integration.go, pagerduty_integration.go
I'm adding this because I would like to use it in the Terraform Provider to have a data source to pull Integration https://github.com/splunk-terraform/terraform-provider-signalfx/pull/274
=> GET PagerDuty Integration By Name

signalflow/computation.go, signalflow/computation_test.go
In some circumstances, the [signalflow stream server](https://dev.splunk.com/observability/docs/signalflow/messages/stream_messages_specification/) can return error messages with a null `message` value
```json
{
"type": "error",
"error": 400,
"errorType": "ANALYTICS_INTERNAL_ERROR",
"message": null
}
```
signalfx-go will panic in this circumstance because it attempts to cast `message`, if present, to string. A nil check on the `message` value avoids the panic.
=> Do not panic on null error message

signalflow/computation.go
Support running signal flow queries like:
```
D = alerts(detector_name='Deployment').publish(label='D')
F = events(eventType='deployment').publish(label='F')
```
=> Return events/alerts from signalflow events/alerts queries

pagerduty_integration.go, pagerduty_integration_test.go, testdata/fixtures/integration/get_by_name_pd_success.json
Signed-off-by: Salvatore Mazzarino <smazzarino@sessionm.com>
Fixing an issue in the URL parsing. `?` could not be parsed correctly. This have as result to not found the integration when the client is used for instance in Terraform provider
=> Fix PagerDuty Integration query

go.mod, sessiontoken/model_create_token_request.go
Without the ability to specify the organizationId in the session token request if the user has accounts in multiple orgs then you cannot control the oragnization id that the token is issued for
Note that the organizationId is also missing from the API spec:
https://dev.splunk.com/observability/reference/api/sessiontokens/latest#endpoint-create-session-token
but definitely exists as we use it in other repos that use curl rather than the go client
=> organizationId is needed in sessiontokenrequest

alertmuting.go, alertmuting_test.go
As per [api documentation](https://dev.splunk.com/observability/reference/api/incidents/latest#endpoint-retrieve-muting-rules-using-query).
=> Fix for search Muting (name is not in api, query is)

alertmuting/model_alert_muting_rule.go
Adds missing attribute based on latest docs (https://dev.splunk.com/observability/reference/api/incidents/latest)
=> Add support for the sendAlertsOnceMutingPeriodHasEnded attribute

client_test.go, metrics_metadata.go, metrics_metadata/model_retrieve_metric_metadata_response_model.go, metrics_metadata_test.go, testdata/fixtures/metrics_metadata/metric_search_success.json
These changes prevent sending the `orderBy` query parameter in remaining search helpers if an empty string is provided (currently triggering an issue with the API).
They also correct what appears to be a typo on the `RetrieveMetricMetadataResponseModel` struct that occurred during the OpenAPI-based helper generation.  As far as I can tell this field has never been named "result" in the product.  This includes a potential breaking change by updating the `Result` field name to `Results` to match the other models and response.  I opted for this change to meet the signatures of the other result models and since it's not been functional I'm not sure how breaking it can actually be considered.
=> Don't send empty orderBy query param and correct metrics search results field

go.mod, go.sum
github.com/gorilla/websocket package, versions <1.4.1 are vulnerable to [CVE-2020-27813](https://nvd.nist.gov/vuln/detail/CVE-2020-27813). 
This updates to the latest version of gorilla/websocket which contains the fix for this issue.
=> Update gorilla/websocket for cve fix

signalflow/conn.go
According to [documentation](https://github.com/signalfx/signalfx-go/blob/6c74a9c6a4a52df5808c02a89da8bb7f0a8ce5cf/signalflow/client.go#L325-L326) after `Client.Close()` is invoked, client should not be used anymore. This behavior is desired.
> Close the client and shutdown any ongoing connections and go routines.  The client cannot be reused after Close.
The problem is when connection is not ready and `Client.Close()` is invoked, context is canceled but reconnect tries[ indefinitely connect to the server without checking context](https://github.com/signalfx/signalfx-go/blob/6c74a9c6a4a52df5808c02a89da8bb7f0a8ce5cf/signalflow/conn.go#L78-L103) status. There is no way to stop go routine.
**Steps to reproduce:**
1. Create client with invalid realm.
2. Close connection with `client.Close()`. …
=> Context cancellation handling

integration/model_aws_service.go
related to https://github.com/splunk-terraform/terraform-provider-signalfx/pull/314 and https://github.com/signalfx/signalfx-go/pull/132 and support ticket 00019838
@dloucasfx @jrcamp @asuresh4 @keitwb
I found the https://app.eu0.signalfx.com/v2/aws/supportedNamespacesAndRegions (undocumented I think). while it requires a token it seems not possible to build the model fully dynamically.
Nevertheless, the manual update of aws and azure services is painful and always done after a customer feedback which is not really a proactive approach.
To clean manually this time I run the following script:
```bash
#!/bin/bash
if ! [ -v SFX_TOKEN ]; then
echo "You must set environment variable \"SFX_TOKEN\""
exit 1
fi
ERR=0
MODEL_FILE="integration/model_aws_service.go" …
```
=> fix robomaker and medialive namespaces

signalflow/fake_backend.go, signalflow/fake_backend_test.go
Timestamps are introduced via the execute request counting up in resolutionMs increments between the startMs time and the stopMs time. When the stopMs is reached the END_OF_CHANNEL is reached.
This makes the fakebackend moure usuable in unit tests since we can have deterministic timestamps and the client can disconnect when the computation all expected datapoints.
Unit tests added to demonstrate this works with multiple clients connecting.
Behaviour of defaults for stopMs and startMs is same as client ie perpetual computation for 0 or empty stopMs and now for empty or 0 startMs
=> signalflow fakebackend support for timestamp control and END_OF_CHANNEL

.gitignore, orgtoken/model_create_update_token_request.go, orgtoken/model_token.go
This repo used to auto-generate the structs from https://github.com/signalfx/api-reference but our api specs repo has been archived and dated, hence the manual update.
For this PR, we need to add `AuthScopes` to the org token struct as this field is required when making changes to an existing token that has `limits` defined.
I also added `.idea` to the gitignore file
Signed-off-by: Dani Louca <dlouca@splunk.com>
=> Adding AuthScopes attribute to the org token struct

aws_cloudwatch_integration_test.go, integration/model_aws_cloud_watch_integration.go, testdata/fixtures/integration/create_aws_metric_streams_success.json
This PR adds support for setting `metricStreamsSyncState`
https://docs.splunk.com/Observability/gdi/get-data-in/connect/aws/aws-apiconfig.html#nav-Connect-to-AWS-using-the-Splunk-Observability-Cloud-API
=> Add MetricStreamsSyncState to AWS Cloudwatch integration

signalflow/computation.go
Previously the messages were not getting fully flushed to the downstream channels
=> signalflow: Fix race in computation buffering when closing

integration/model_gcp_integration.go, integration/model_gcp_integration_test.go
Whitelist field is deprecated and will be replaced
with includeList field. This is a backward compatible
solution that replaces whitelist with includeList
=> Add includeList to GCP integration

incident.go, incident_test.go, testdata/fixtures/incident/get_incident.json, testdata/fixtures/incident/get_incidents.json
Add two functions `GetIncident` and `GetIncidents` which retrieve incidents using the `/v2/incident/` api. Currently there is only support to get incidents based on detector ids.
=> New functions to retrieve incidents

CHANGELOG.md, integration/model_gcp_integration.go
Hi folks! I'm going to use field `customMetricTypeDomains` which I've got from [the official docs](https://dev.splunk.com/observability/docs/integrations/gcp_integration_overview/#Request-body-for-POST-v2integration) in the Terraform provider [splunk-terraform/signalfx](https://github.com/splunk-terraform/terraform-provider-signalfx).
Issue: https://github.com/signalfx/signalfx-go/issues/181
=> Add `customMetricTypeDomains` field to the `GCPIntegration` struct

signalflow/client.go, signalflow/computation.go
The stop job function is currently broken on the backend, this causes applications that use `Stop()` to leak jobs which leads to various problems. ex: https://github.com/signalfx/signalfx-k8s-metrics-adapter
The recommended way is to use `detach` func instead, which this PR adds.
cc: @kchengsf
=> add signalflow detach func

.github/workflows/test.yml, signalflow/fake_backend.go
Previous https://github.com/signalfx/signalfx-go/pull/186 added support to detach, this PR adds the detach to the fakebackend which is used for testing in https://github.com/signalfx/signalfx-k8s-metrics-adapter/blob/main/internal/integration_test.go
=> Add detach to FakeBackend which now supports both, stop and detach

organization/model_organization.go
when making the following call, which returns the current organization:
```
result, err := s.sfxClient.GetOrganization(s.ctx, "")
```
It fails with the following error:
```
panic: json: cannot unmarshal bool into Go struct field Organization.accountRenews of type string
```
This patch changes the type of accountRenews to be a bool so that I can use the GetOrganization methods.
=> fix organization model struct

signalflow/computation.go
Certain types of jobs can cause the resolution info message to be sent twice for some reason, causing a panic on the close channel for the asyncMetadata.Set call
=> signalflow client: Handle receipt of duplicate info messages without crashing

slo.go, slo/model_slo_alert_rule_object.go, slo/model_slo_object.go, slo/model_slo_target.go, slo_test.go, testdata/fixtures/slo/get_success_calendar_window_target.json, testdata/fixtures/slo/get_success_rolling_window_target.json
Add model files for slo resource and enhance go client with methods related to SLO resource
=> slo: add methods related to slo resource

writer/README.md, writer/internal.go
Our clients should use https://github.com/open-telemetry/opentelemetry-go or https://github.com/signalfx/splunk-otel-go instead of https://pkg.go.dev/github.com/signalfx/signalfx-go/writer. Let's make it clear.
=> Deprecate writer package

README.md, signalflow/README.md, signalflow/doc.go, signalflow/example/main.go, signalflow/go.mod
Deprecate signaflow module in favor of https://github.com/signalfx/signalflow-client-go/releases/tag/v2.3.0
=> Deprecate signalflow

detector/model_authorized_writers.go, detector/model_create_detector_request.go, detector/model_detector.go
detector: change detector model to allow sending empty array fields
In detector API in order to remove all teams or tags from detector resource user has to send an empty array.
=> detector: change detector model to allow sending empty array fields

detector/model_detector.go, testdata/fixtures/detector/get_success.json, testdata/fixtures/detector/search_success.json, testdata/fixtures/detector/update_success.json
detector: extend detector model with detectorOrigin and parentDetectorId fields
=> detector: extend detector model with detectorOrigin and parentDetectorId fields

incident.go
Check response code before unmarshaling response.Body. Sometimes the response code is 400 and the unmarshall errors out. This ensures that the errors are handled properly.
=> Check response code for errors

detector/model_create_detector_request.go, detector/model_validate_detector_request_model.go
detector: extend detector create model with detectorOrigin and parentDetectorId
=> detector: extend detector create model with detectorOrigin and parentDetectorId

alertmuting.go, aws_cloudwatch_integration.go, azure_integration.go, chart.go, dashboard.go, dashboardgroup.go, datalink.go, detector.go, errors.go, errors_test.go, gcp_integration.go, incident.go, integration.go, jira_integration.go, metric_ruleset.go, metrics_metadata.go, opsgenie_integration.go, organization.go, orgtoken.go, pagerduty_integration.go, sessiontoken.go, slack_integration.go, slo.go, team.go, victor_ops_integration.go, webhook_integration.go
To help simplify and address how errors from responses are handled, this returns an error type that allows for deeper introspection from external packages.
This is helpful in projects like the signalfx-terraform-provider since it currently determines type of error by searching the error message for the expected status code, this could improve by returning a more complex error type to provide the improved level of introspection.
- Standardize all response errors by adopting `ResponseError`
- Adding new error type `ResponseError` with methods to create and inspect.
- Removed check for resp not being nil to close body.
=> Feature: Adding standardize response error

chart.go, chart_test.go, dashboard.go, dashboard_test.go, dashboardgroup.go, dashboardgroup_test.go, slo.go
Functions for validation added for charts, dashboards and dashboard groups. Code is refactored to remove duplicated code. Minor update for `executeSloRequest` function to return error instead of nil.
=> Add validation for viz objects

integration/model_aws_cloud_watch_integration.go
This is a new field that intended to be added into the terraform provider.
- Added `CollectOnlyRecommendedStats` to AWS cloudwatch Integration
=> Feature: Adding `CollectOnlyRecommendedOnly` to AWS Integration

detector.go, detector_test.go, testdata/fixtures/detector/get_detectors.json
This merge request adds code that sends a GET request to the `/v2/detector` endpoint documented in the following page: https://dev.splunk.com/observability/reference/api/detectors/latest#endpoint-retrieve-detectors-query
This follows the same pattern used in the other endpoints for retrieving objects with the signalfx API. Changes have been tested locally to insure that it works as intended.
=> Retrieve all detectors

detector.go
Merge request fixes a problem with the GetDetectors method. Currently the function accepts the params but never utilizes it.
The c.doRequest() now includes the params passed
=> Updated GetDetectors to utilze the params provided

integration/model_splunk_platform_integration.go, integration/model_type.go, notification/model_notification.go, notification/model_notification_test.go, notification/model_splunk_platform_notification.go, testdata/fixtures/detector/get_detectors.json
I was unable to fetch detectors from my org as notification on one of the detectors was of the type [SplunkPlatform](https://docs.splunk.com/observability/en/admin/notif-services/splunkplatform.html) and the signalfx-go module does not support it right now.
I have also added support form the Splunk Platform Integration.
=> Added support for Splunk Platform Integration and Notification

integration/model_aws_cloud_watch_integration.go
This adds a field that is used for the AWS integration to enable externally managed AWS metric streams.
- Added filed `MetricStreamsManagedExternally` to AWS integration type.
=> Feature: Adding field to AWS Integration

organization.go, organization_test.go
This PR fixes a bug in the `GetOrganization` method. The Splunk Observability API does not accept an OrgID as part of the path, it infers the org from the token and endpoint. I tested this code locally and it works with this change.
=> Fix GetOrganization to not require OrgID
