- client.go
- client_test.go
> Include content-type header

- chart.go
- chart_test.go
Use response codes to generate proper errors for chart operations.
Left it out of #8
> Use response codes for charts and test them

- dashboard.go
- dashboard_test.go
> Honor status on dashboard get

- dashboard/model_create_update_dashboard_request.go
Adds tags to dashboard request.
> Add tags to dashboard create request

- dashboard/model_charts_filters.go
- dashboard/model_charts_single_filter.go
- dashboard/model_charts_web_ui_filter.go
More dashboard fixes for missing fields and pointers
> More dash fixes

- dashboard/model_create_update_dashboard_request.go
- dashboard/model_dashboard.go
- testdata/fixtures/dashboard/create_success.json
- testdata/fixtures/dashboard/get_success.json
- testdata/fixtures/dashboard/search_success.json
- testdata/fixtures/dashboard/update_success.json
Fixes some errors from the original spec.
> Fix errors pulled from original spec.

- chart/model_general_options.go
- testdata/fixtures/chart/create_success.json
- testdata/fixtures/chart/get_success.json
- testdata/fixtures/chart/update_success.json
> Add timezone to chart programOptions

- team.go
- team_test.go
Adds proper status checks to some team operations
I keep forgetting these. :(
> Add status checks for team operations

- organization.go
- organization/model_invite_member_request.go
- organization_test.go
- testdata/fixtures/organization/update_member_success.json
Add member update method
This wasn't implemented and wasn't documented, so I implemented it. Also updated the struct to have a name consistent with others.
> Add member updates

- organization.go
- organization_test.go
- testdata/fixtures/organization/update_member_success.json
> Doesn't work, remove it!

- dashboard/model_charts_web_ui_filter.go
Fix type of `dashboard.filters.variables.value`
Flagged by @doctornkz in #31
> Fix filter value

- CHANGELOG.md
- dashboard/model_charts_single_filter.go
- dashboard/model_charts_web_ui_filter.go
- dashboard/model_event_overlay_filter.go
- dashboard/model_simple_dashboard_model.go
- dashboard_group/model_dashboard_config.go
- dashboard_group/model_filter.go
- dashboard_group/model_filters.go
- dashboard_group/model_search_result.go
- dashboard_group/model_web_ui_filter.go
- util/string_or_slice.go
Clean up some dashbooard and dashboard group types
In looking into dashboard group creation I found some missing pointers types. Also learned from past mistakes and am using `StringOrSlice` preemptively.
> Fix pointer types and more

- CHANGELOG.md
- dashboard_group/model_create_update_dashboard_group_request.go
> Add DashboardConfigs to create/update request

- CHANGELOG.md
- dashboardgroup.go
- dashboardgroup_test.go
Allows option to skip creation of the implicit dashboard that comes with a group.
> Allow a choice of implicit dashboard creation on a dashboard group

- dashboard_group/model_dashboard_config.go
> Fix bad json name for dashboardConfigs.filters

- CHANGELOG.md
- gcp_integration.go
- gcp_integration_test.go
- integration/model_gcp_integration.go
- integration/model_gcp_project.go
- integration/model_opsgenie_integration.go
- opsgenie_integration.go
- opsgenie_integration_test.go
- pagerduty_integration.go
- pagerduty_integration_test.go
- slack_integration.go
- slack_integration_test.go
- testdata/fixtures/integration/create_gcp_success.json
- testdata/fixtures/integration/create_opsgenie_success.json
- testdata/fixtures/integration/create_pd_success.json
- testdata/fixtures/integration/create_slack_success.json
Add methods for additional integrations.
Terraform!
> Add more integration methods

- chart/model_event_publish_label_options.go
> Adjust type of EPLO color to match others

- CHANGELOG.md
- testdata/fixtures/integration/create_victor_ops_success.json
- victor_ops_integration.go
- victor_ops_integration_test.go
> Add VictorOps functions

- CHANGELOG.md
- detector/model_time.go
This is an error, should be int64!
> Fix detector end, start and range to be int64

- CHANGELOG.md
- dashboard/model_dashboard_event_signal.go
> Add detector id to event overlays

- CHANGELOG.md
- datalink.go
- datalink/model_create_update_data_link_request.go
- datalink/model_data_link.go
- datalink/model_search_results.go
- datalink/model_target.go
- datalink/model_timeformat.go
- datalink/model_type.go
- datalink_test.go
- testdata/fixtures/datalink/create_success.json
- testdata/fixtures/datalink/get_success.json
- testdata/fixtures/datalink/search_success.json
- testdata/fixtures/datalink/update_success.json
- util/string_or_integer.go
> Add Data Links

- datalink_test.go
This should fix the currently failing tests (https://circleci.com/gh/signalfx/signalfx-go/tree/master)
> Fix data links test failures

- detector.go
- detector/model_event.go
- detector/model_incident.go
- detector_test.go
- testdata/fixtures/detector/get_events.json
- testdata/fixtures/detector/get_incidents.json
What is says on the tin.
Fixes #67
> Add new methods GetDetectorEvents and GetDetectorIncidents

- CHANGELOG.md
- testdata/fixtures/integration/create_webhook_success.json
- webhook_integration.go
- webhook_integration_test.go
> Add Webhook integration functions

- CHANGELOG.md
- realm/urls.go
- realm/urls_test.go
It was starting to get repeated a lot of times in various projects.
> Add some realm config helpers to centralize this logic

- dashboard/model_create_update_dashboard_request.go
- dashboard/model_dashboard.go
- dashboard/model_discovery_options.go
- dashboard_group/model_create_update_dashboard_group_request.go
- dashboard_group/model_dashboard_group.go
- dashboard_group/model_import_filter.go
- dashboard_group/model_import_qualifier.go
Adds new options
Want to support creation/export of built in content.
> Add discoveryOptions and importQualifier

- signalflow/computation.go
- signalflow/computation_test.go
- signalflow/messages/info.go
From https://developers.signalfx.com/signalflow_analytics/rest_api_messages/information_messages_specification.html#_message_code_reference
> add computation MatchedSize() and LimitSize()

- CHANGELOG.md
- metrics_metadata.go
> Fix Dimension Search

- CHANGELOG.md
- integration/model_azure_service.go
> Add some azure services

- CHANGELOG.md
- signalflow/client_test.go
- signalflow/fake_backend.go
The resolution reported for the job is the maximum resolution of all of the tsids matched by
a program.
> More realistic resolution handling in fake signalflow client

- CHANGELOG.md
- chart.go
- chart_test.go
- dashboard.go
- dashboard_test.go
- dashboardgroup.go
- dashboardgroup_test.go
- datalink.go
- datalink_test.go
- detector.go
- detector_test.go
- metrics_metadata.go
- metrics_metadata_test.go
- organization.go
- organization_test.go
- orgtoken.go
- orgtoken_test.go
- team.go
- team_test.go
What is says on the tin. Fixes #83
> Add status code checks to various search methods

- CHANGELOG.md
- integration/model_gcp_integration.go
- integration/model_gcp_service.go
Convert GCP to services to be a type just like the other integrations.
> Add GCP Services

- integration/model_aws_cloud_watch_integration.go
- integration/model_azure_integration.go
- integration/model_gcp_integration.go
> Add named token to integrations

- signalflow/computation.go
- signalflow/computation_test.go
- signalflow/messages/info.go
Sry @cory-signalfx, you were too fast for me (:
Here's the rest of https://github.com/signalfx/signalfx-go/pull/92.
> Parse Content from Info Messages

- writer/datapoint_writer.gen.go
- writer/span_writer.gen.go
- writer/template/writer.go
The writer's ring buffer may have not been initialized inside its go routine before another routine may call the `InternalMetrics` function, which accesses the writer's ring buffer, causing a panic.
This PR moves the initialization of several writer fields into the writer's `Start` function, before the new go routine is created to run the writer.
> Move initialization of writer fields outside of go routine

- team.go
- team_test.go
Adds new methods for team linking.
The inline versions of these are being deprecated.
> Add new team linking methods

- integration/model_aws_service.go
Signed-off-by: Dani Louca <dlouca@splunk.com>
> Fix AWS Glue namespace

- integration/model_aws_service.go
Add AWS/WAFV2, CWAgent, AWS/Backup
> Add newly supported AWS services to the list.

- CHANGELOG.md
- detector/model_visualization.go
This PR is to changing ShowDataMarker to use pointers to allow differentiating between false and nil variables.
> Remove `omitempty` from ShowDataMarker

- detector/model_incident.go
- incident_test.go
- testdata/fixtures/incident/get_incident.json
- testdata/fixtures/incident/get_incidents.json
* Added three hidden fields that are returned by the `/v2/incident` API:
1) isMuted
2) triggeredNotificationSent
3) triggeredWhileMuted
* Modified the `TestGetIncident` test case to check all fields
> Add some hidden incident fields that are returned by the /v2/incident API

- integration/model_azure_service.go
Hello,
This PR adds the PostgreSQL flexible, Recovery Vault & Backup Vault services to the supported Azure services list.
Closes #191 #192 #193
> Add Azure services PostgreSQL flexible, Recovery Vault & Backup Vault

- signalflow/computation.go
- signalflow/computation_test.go
This correctly re-implements the events output that was done incorrectly in the original v1 signalflow client.
> Add events channel to SignalFlow computations

- notification/model_notification.go
- notification/model_notification_test.go
It looks like there wasn't any existing tests for this package, this will at least ensure going forward that these are correctly Unmarshaled.
- Added tests to notifications.
> [chore]: Adding tests to notification marshalling

- detector/model_reminder_notification.go
- detector/model_rule.go
- detector_test.go
- testdata/fixtures/detector/create_success.json
This PR adds a possibility to define Reminder Notification per detector rule.
> Feature: Add reminder notification for detector rule
